CFLAGS="${CFLAGS_NO_LTO}"
CXXFLAGS="${CFLAGS_NO_LTO}"
FFLAGS="${FFLAGS_NO_LTO}"
FCFLAGS="${FFLAGS_NO_LTO}"

LDFLAGS="${LDFLAGS_NO_LTO}"

RUSTFLAGS="--codegen opt-level=2 --codegen target-cpu=goldmont-plus"
