CFLAGS="${CFLAGS} -O3 -mllvm -polly -mllvm -polly-vectorizer=stripmine -mllvm -polly-invariant-load-hoisting"
CXXFLAGS="${CXXFLAGS} -O3 -mllvm -polly -mllvm -polly-vectorizer=stripmine -mllvm -polly-invariant-load-hoisting"

LDFLAGS="${LDFLAGS} -Wl,--lto-O3"
