FEATURES="ccache"
CCACHE_DIR="/var/cache/ccache"
CCACHE_BASEDIR="${WORKDIR:-/var/tmp/portage}"

CC="ccache clang"
CXX="ccache clang++"
HOSTCC="ccache clang"
HOSTCXX="ccache clang++"

KBUILD_BUILD_TIMESTAMP=''
