CFLAGS="${CFLAGS_NO_LTO} -flto=full"
CXXFLAGS="${CFLAGS_NO_LTO} -flto=full"
FFLAGS="${FFLAGS_NO_LTO} -flto=full"
FCFLAGS="${FFLAGS_NO_LTO} -flto=full"

LDFLAGS="${LDFLAGS_NO_LTO} -flto=full -Wl,--lto-O3"
