CC="gcc"
CXX="g++"
CPP="gcc -E"
AR="ar"
NM="nm"
RANLIB="ranlib"
LD="ld.bfd"

CFLAGS="-fdata-sections -ffunction-sections -flto -fno-asynchronous-unwind-tables -fno-math-errno -fno-plt -fno-semantic-interposition -fno-trapping-math -march=x86-64-v3 -O3 -pipe"
CXXFLAGS="${CFLAGS}"

LDFLAGS="${ORIGINAL_LDFLAGS} ${CFLAGS} -fuse-ld=bfd -Wl,--gc-sections"

RUSTFLAGS="--codegen target-cpu=x86-64-v3"

CGO_CFLAGS="${CFLAGS}"
CGO_CXXFLAGS="${CXXFLAGS}"

QMAKESPEC="linux-g++"
