name: 1 Benchmark

on:
  workflow_dispatch:

env:
  BUNNY_STORAGE_ACCESS_KEY: ${{ secrets.BUNNY_STORAGE_ACCESS_KEY }}
  BUNNY_STORAGE_CDN: ${{ secrets.BUNNY_STORAGE_CDN }}
  BUNNY_STORAGE_ENDPOINT: ${{ secrets.BUNNY_STORAGE_ENDPOINT }}
  BUNNY_STORAGE_ENDPOINT_CDN: ${{ secrets.BUNNY_STORAGE_ENDPOINT_CDN }}
  BUNNY_STORAGE_ZONE_NAME: ${{ secrets.BUNNY_STORAGE_ZONE_NAME }}
  CONFIG_PREFIX: 1
  POWERSHELL_7_ARCHITECTURE: x64
  PACKAGES: net-libs/nodejs

jobs:
  emerge:
    name: Emerge
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install PowerShell
        run: sudo --preserve-env bash ./install-powershell.sh

      - name: Set Up Gentoo
        run: sudo --preserve-env pwsh -File ./Start-CopyImage.ps1 -From

      - name: Set Up Binary Packages
        run: sudo --preserve-env pwsh -File ./Start-CopyBinaryPackages.ps1 -From

      - name: Mount Filesystems
        run: sudo --preserve-env pwsh -File ./Start-MountFilesystems.ps1

      - name: Emerge
        run: sudo --preserve-env chroot /mnt/gentoo bash /mnt/emerge.sh --packages "$PACKAGES"

      - name: Run Benchmarks
        run: |
          sudo --preserve-env git clone https://github.com/Whileone-Techsoft/JetStream-Node.git /mnt/gentoo/tmp/JetStream-Node
          cd /mnt/gentoo/tmp/JetStream-Node
          sudo --preserve-env git checkout jetstream-on-node-js-v2
          cd -
          sudo --preserve-env chroot /mnt/gentoo bash -c "cd /tmp/JetStream-Node; npm run jetstream-node all"

      - name: Emerge
        run: sudo --preserve-env chroot /mnt/gentoo bash /mnt/emerge.sh --packages "$PACKAGES" --usepkg-exclude "$PACKAGES"

      - name: Run Benchmarks
        run: |
          sudo --preserve-env chroot /mnt/gentoo bash -c "cd /tmp/JetStream-Node; npm run jetstream-node all"

      - name: Unmount Filesystems
        if: always()
        run: sudo --preserve-env pwsh -File ./Start-MountFilesystems.ps1 -Unmount
