name: 1 Emerge CRIU Firefox

on:
  workflow_dispatch:

env:
  BUNNY_STORAGE_ACCESS_KEY: ${{ secrets.BUNNY_STORAGE_ACCESS_KEY }}
  BUNNY_STORAGE_CDN: ${{ secrets.BUNNY_STORAGE_CDN }}
  BUNNY_STORAGE_ENDPOINT: ${{ secrets.BUNNY_STORAGE_ENDPOINT }}
  BUNNY_STORAGE_ENDPOINT_CDN: ${{ secrets.BUNNY_STORAGE_ENDPOINT_CDN }}
  BUNNY_STORAGE_ZONE_NAME: ${{ secrets.BUNNY_STORAGE_ZONE_NAME }}
  CONFIG_PREFIX: 1
  POWERSHELL_7_ARCHITECTURE: x64
  PACKAGES: www-client/firefox

jobs:
  emerge:
    name: Emerge
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install PowerShell
        run: sudo --preserve-env bash ./install-powershell.sh

      - name: Install CRIU
        run: sudo --preserve-env pwsh -File ./Start-InstallCriu.ps1

      - name: Set Up Gentoo
        run: sudo --preserve-env pwsh -File ./Start-CopyImage.ps1 -From

      - name: Set Up Binary Packages
        run: sudo --preserve-env pwsh -File ./Start-CopyBinaryPackages.ps1 -From

      - name: Mount Filesystems
        run: sudo --preserve-env pwsh -File ./Start-MountFilesystems.ps1

      - name: Emerge
        run: |
          export FEATURES="-ipc-sandbox -network-sandbox -pid-sandbox"

          sudo --preserve-env chroot /mnt/gentoo bash /mnt/emerge.sh --packages "$PACKAGES"

          pid=$!

          sleep "360" &

          sleep_pid=$!

          wait -n "$pid" "$sleep_pid"

          if sudo kill -0 $pid; then
            mkdir /mnt/gentoo/var/lib/criu

            criu dump --images-dir /mnt/gentoo/var/lib/criu --shell-job --tree "$pid"

            exit 1
          fi

      - name: Unmount Filesystems
        if: always()
        run: sudo --preserve-env pwsh -File ./Start-MountFilesystems.ps1 -Unmount

      - name: Upload Gentoo Binary Packages
        if: always()
        run: sudo --preserve-env pwsh -File ./Start-CopyBinaryPackages.ps1 -To

      - name: Upload Gentoo
        if: failure()
        run: sudo --preserve-env pwsh -File ./Start-CopyImage.ps1 -To -Temporary
