name: 1 Emerge GNOME

on:
  workflow_dispatch:

env:
  BUNNY_STORAGE_ACCESS_KEY: ${{ secrets.BUNNY_STORAGE_ACCESS_KEY }}
  BUNNY_STORAGE_CDN: ${{ secrets.BUNNY_STORAGE_CDN }}
  BUNNY_STORAGE_ENDPOINT: ${{ secrets.BUNNY_STORAGE_ENDPOINT }}
  BUNNY_STORAGE_ENDPOINT_CDN: ${{ secrets.BUNNY_STORAGE_ENDPOINT_CDN }}
  BUNNY_STORAGE_ZONE_NAME: ${{ secrets.BUNNY_STORAGE_ZONE_NAME }}
  CONFIG_PREFIX: 1
  POWERSHELL_7_ARCHITECTURE: x64
  PACKAGES: app-crypt/seahorse app-editors/gnome-text-editor gnome-base/gnome-light gnome-extra/gnome-calculator gnome-extra/gnome-clocks gnome-extra/gnome-logs gnome-extra/gnome-shell-extension-appindicator gnome-extra/gnome-system-monitor gnome-extra/gnome-tweaks media-gfx/eog media-gfx/simple-scan sci-geosciences/gnome-maps

jobs:
  emerge:
    name: Emerge
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install PowerShell
        run: sudo --preserve-env bash ./install-powershell.sh

      - name: Set Up Gentoo
        run: sudo --preserve-env pwsh -File ./Copy-GentooImage.ps1 -From

      - name: Set Up Binary Packages
        run: sudo --preserve-env pwsh -File ./Copy-GentooBinaryPackage.ps1 -From

      - name: Mount Filesystems
        run: sudo --preserve-env pwsh -File ./Start-MountFilesystems.ps1

      - name: Emerge
        run: sudo --preserve-env chroot /mnt/gentoo bash /mnt/emerge.sh --packages "$PACKAGES"

      - name: Unmount Filesystems
        if: always()
        run: sudo --preserve-env pwsh -File ./Start-MountFilesystems.ps1 -Unmount

      - name: Upload Gentoo Binary Packages
        if: always()
        run: sudo --preserve-env pwsh -File ./Copy-GentooBinaryPackage.ps1 -To

      - name: Upload Gentoo
        if: failure()
        run: sudo --preserve-env pwsh -File ./Copy-GentooImage.ps1 -To -Temporary
