name: 2 Emerge oneAPI Other

on:
  workflow_dispatch:

env:
  BUNNY_STORAGE_ACCESS_KEY: ${{ secrets.BUNNY_STORAGE_ACCESS_KEY }}
  BUNNY_STORAGE_CDN: ${{ secrets.BUNNY_STORAGE_CDN }}
  BUNNY_STORAGE_ENDPOINT: ${{ secrets.BUNNY_STORAGE_ENDPOINT }}
  BUNNY_STORAGE_ENDPOINT_CDN: ${{ secrets.BUNNY_STORAGE_ENDPOINT_CDN }}
  BUNNY_STORAGE_ZONE_NAME: ${{ secrets.BUNNY_STORAGE_ZONE_NAME }}
  CONFIG_PREFIX: 2
  PACKAGES: net-misc/moonlight
  USEPKG_EXCLUDE: net-misc/moonlight

jobs:
  emerge:
    name: Emerge
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install PowerShell
        run: sudo --preserve-env bash ./install-powershell.sh

      - name: Set Up Gentoo
        run: sudo --preserve-env pwsh -File ./Copy-GentooImage.ps1 -From

      - name: Set Up Binary Packages
        run: sudo --preserve-env pwsh -File ./Copy-GentooBinaryPackage.ps1 -From

      - name: Install Intel oneAPI DPC++/C++ Compiler
        run: sudo --preserve-env pwsh -File ./Initialize-OneapiDcp++C++Compiler.ps1

      - name: Mount Filesystems
        run: sudo --preserve-env pwsh -File ./Mount-GentooFilesystem.ps1

      - name: Set Up Emerge
        run: sudo --preserve-env pwsh -File ./Initialize-GentooEmerge.ps1

      - name: Emerge
        run: sudo --preserve-env chroot /mnt/gentoo pwsh -File /mnt/Invoke-GentooEmerge.ps1 -Packages "$PACKAGES" -UsePkgExclude "$USEPKG_EXCLUDE"

      - name: Clean Up Emerge
        if: always()
        run: sudo --preserve-env pwsh -File ./Initialize-GentooEmerge.ps1 -Clean

      - name: Unmount Filesystems
        if: always()
        run: sudo --preserve-env pwsh -File ./Dismount-GentooFilesystem.ps1

      - name: Upload Gentoo Binary Packages
        if: always()
        run: sudo --preserve-env pwsh -File ./Copy-GentooBinaryPackage.ps1 -To

      - name: Upload Gentoo
        if: failure()
        run: sudo --preserve-env pwsh -File ./Copy-GentooImage.ps1 -To -Temporary
