name: 1 Bootstrap 3

on:
  workflow_dispatch:

env:
  BUNNY_STORAGE_ACCESS_KEY: ${{ secrets.BUNNY_STORAGE_ACCESS_KEY }}
  BUNNY_STORAGE_ENDPOINT: ${{ secrets.BUNNY_STORAGE_ENDPOINT }}
  BUNNY_STORAGE_ENDPOINT_CDN: ${{ secrets.BUNNY_STORAGE_ENDPOINT_CDN }}
  BUNNY_STORAGE_ZONE_NAME: ${{ secrets.BUNNY_STORAGE_ZONE_NAME }}
  CONFIG_PREFIX: 1

jobs:
  emerge:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install PowerShell
        run: sudo bash ./install-powershell.sh

      - name: Set Up Gentoo
        run: sudo pwsh ./Copy-Gentoo.ps1 -From -Bootstrap

      - name: Set Up Binary Packages
        run: sudo pwsh ./Copy-GentooBinaryPackages.ps1 -From

      - name: Mount Filesystems
        run: sudo pwsh ./Mount-Gentoo.ps1

      - name: Emerge
        run: sudo pwsh ./Invoke-Gentoo.ps1 -Packages "llvm-runtimes/libunwind sys-kernel/gentoo-kernel net-vpn/ovpn-dco"

      - name: Unmount Filesystems
        if: always()
        run: sudo pwsh ./Dismount-Gentoo.ps1

      - name: Upload Gentoo Binary Packages
        run: sudo pwsh ./Copy-GentooBinaryPackages.ps1 -To

      - name: Upload Gentoo
        if: success() || failure()
        run: sudo pwsh ./Copy-Gentoo.ps1 -To
