name: 1 Update

on:
  workflow_dispatch:

env:
  BUNNY_STORAGE_ACCESS_KEY: ${{ secrets.BUNNY_STORAGE_ACCESS_KEY }}
  BUNNY_STORAGE_ENDPOINT: ${{ secrets.BUNNY_STORAGE_ENDPOINT }}
  BUNNY_STORAGE_ENDPOINT_CDN: ${{ secrets.BUNNY_STORAGE_ENDPOINT_CDN }}
  BUNNY_STORAGE_ZONE_NAME: ${{ secrets.BUNNY_STORAGE_ZONE_NAME }}
  CONFIG_PREFIX: 1

jobs:
  update:
    name: Update
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install PowerShell
        run: sudo --preserve-env bash ./install-powershell.sh

      - name: Set Up Gentoo
        run: sudo --preserve-env pwsh -File ./Copy-GentooImage.ps1 -From

      - name: Set Up Binary Packages
        run: sudo --preserve-env pwsh -File ./Copy-GentooBinaryPackage.ps1 -From

      - name: Mount Filesystems
        run: sudo --preserve-env pwsh -File ./Mount-GentooFilesystem.ps1

      - name: Set Up Emerge
        run: sudo --preserve-env pwsh -File ./Initialize-GentooEmerge.ps1

      - name: Emerge
        run: sudo --preserve-env chroot /mnt/gentoo pwsh -File /mnt/Invoke-GentooEmerge.ps1 -Update

      - name: Clean Up Emerge
        if: always()
        run: sudo --preserve-env pwsh -File ./Initialize-GentooEmerge.ps1 -Clean

      - name: Unmount Filesystems
        if: always()
        run: sudo --preserve-env pwsh -File ./Dismount-GentooFilesystem.ps1

      - name: Upload Gentoo Binary Packages
        run: sudo --preserve-env pwsh -File ./Copy-GentooBinaryPackage.ps1 -To -NoOverlay

      - name: Upload Gentoo
        run: sudo --preserve-env pwsh -File ./Copy-GentooImage.ps1 -To
