name: 2 Fix

on:
  workflow_dispatch:

env:
  BUNNY_STORAGE_ACCESS_KEY: ${{ secrets.BUNNY_STORAGE_ACCESS_KEY }}
  BUNNY_STORAGE_ENDPOINT: ${{ secrets.BUNNY_STORAGE_ENDPOINT }}
  BUNNY_STORAGE_ENDPOINT_CDN: ${{ secrets.BUNNY_STORAGE_ENDPOINT_CDN }}
  BUNNY_STORAGE_ZONE_NAME: ${{ secrets.BUNNY_STORAGE_ZONE_NAME }}
  CONFIG_PREFIX: 2

jobs:
  fix:
    name: Fix
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install PowerShell
        run: sudo --preserve-env bash ./install-powershell.sh

      - name: Set Up Gentoo
        run: sudo --preserve-env pwsh -File ./Copy-GentooImage.ps1 -From -Bootstrap

      - name: Fix
        run: sudo pwsh -Command Remove-Item -Path /mnt/gentoo/var/cache/binpkgs/* -Recurse

      - name: Upload Gentoo
        run: sudo --preserve-env pwsh -File ./Copy-GentooImage.ps1 -To
